[2025-09-11 12:16:17,569] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T12:16:16.121983+00:00 [queued]>
[2025-09-11 12:16:17,578] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T12:16:16.121983+00:00 [queued]>
[2025-09-11 12:16:17,579] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 12:16:17,579] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2025-09-11 12:16:17,579] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2025-09-11 12:16:17,592] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): move_images> on 2025-09-11 12:16:16.121983+00:00
[2025-09-11 12:16:17,596] {standard_task_runner.py:52} INFO - Started process 6974 to run task
[2025-09-11 12:16:17,598] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Daily_img_transfer', 'move_images', 'manual__2025-09-11T12:16:16.121983+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpw0tvv0ha', '--error-file', '/tmp/tmp_q9mp7x6']
[2025-09-11 12:16:17,599] {standard_task_runner.py:80} INFO - Job 49: Subtask move_images
[2025-09-11 12:16:17,639] {task_command.py:370} INFO - Running <TaskInstance: Daily_img_transfer.move_images manual__2025-09-11T12:16:16.121983+00:00 [running]> on host 225d5ec060dd
[2025-09-11 12:16:17,689] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Daily_img_transfer
AIRFLOW_CTX_TASK_ID=move_images
AIRFLOW_CTX_EXECUTION_DATE=2025-09-11T12:16:16.121983+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-09-11T12:16:16.121983+00:00
[2025-09-11 12:16:17,690] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2025-09-11 12:16:17,691] {subprocess.py:74} INFO - Running command: ['bash', '-c', 's\n                               cd ../..\n                               pwd\n                               ']
[2025-09-11 12:16:17,698] {subprocess.py:85} INFO - Output:
[2025-09-11 12:16:17,700] {subprocess.py:92} INFO - bash: line 1: s: command not found
[2025-09-11 12:16:17,701] {subprocess.py:92} INFO - /
[2025-09-11 12:16:17,702] {subprocess.py:96} INFO - Command exited with return code 0
[2025-09-11 12:16:17,722] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Daily_img_transfer, task_id=move_images, execution_date=20250911T121616, start_date=20250911T121617, end_date=20250911T121617
[2025-09-11 12:16:17,770] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-09-11 12:16:17,799] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
